### ISSUE TITLE
UncaughtException: Cannot read property 'splice' of undefined every 30 min

### ISSUE THREAD

**Issue by luk84s** [getbraincloud/brainclouds2s-node#20]
Wrong request() params in startHeartbeat function.
Is: 
```
request({
            service: "heartbeat",
            operation: "HEARTBEAT",
            data: null
        }, data =>
        {
            if (!(data && data.status === 200))
            {
                exports.disconnect(context)
            }
        })
```
        
Should be:
```
 request(context, {
            service: "heartbeat",
            operation: "HEARTBEAT",
            data: null
        }, data =>
        {
            if (!(data && data.status === 200))
            {
                exports.disconnect(context)
            }
        })
```
        
 Missing the "context" param.
 

Second issue is thet heartbeat callback doesn't contains data.status and always execute exports.disconnect(context) 😢 
but after fixing the callback data [added (context, data) => as a callback params] we received error: 
```
{
  "status_message": "Internal server error (bundle): null",
  "severity": "ERROR",
  "status": 500
}
```
 
 Suggestion: You can remove the console.log("Heartbeat")  😉

**Comment by davidstl** [comment]
Thanks for reporting, we'll look into it. When did it start happening for you? Is it 4.8 released yesterday?

**Comment by luk84s** [comment]
It start happening yesterday but we upgraded to version 4.7
